services:
  # A Docker web service
  - type: web
    name: goapp
    buildCommand: docker build -t my-go-app .
    startCommand: docker run -p 3000:3000 my-go-app
    env:
      - key: PORT
        value: 3000

  # Adminer to manage the database
  - type: web
    name: adminer
    image: adminer
    ports:
      - 8080

databases:
  - name: my-postgres-db
    user: docker
    password: docker
    port: 5432
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    volumes:
      - name: db-data
        path: /var/lib/postgresql/data
